### ISSUE TITLE
Working with C# OmniSharp debugging and syntax highlighting?

### ISSUE THREAD

**Issue by chrisError** [Geri-Borbas/VSCode.Extension.eppz_Code#1]
The syntax highlighting works perfectly, but I cannot seem to get it to play nicely with C# debugging / legacy C# debugging.

To replicate:
+ Install [**eppz! (C# Theme for Unity)** 1.0.29](https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code) extension
+ Install **Legacy C# Support** extension (from Microsoft, which is generally the best for Unity)
+ Select **eppz!** Color theme

You will now see that the syntax / code coloring (from eppz! theme) is not working / active.

**Comment by Geri-Borbas** [comment]
Could you please specify version number(s), and possibly what other extensions are installed? I don't find **Legacy C# Support** extension in the marketplace.

You can find a list with identifiers and version numbers at `~/.vscode/extensions` folder. May post it here.

Also, **how you managed to resolve the issue?** May help others.

**Comment by Geri-Borbas** [comment]
Theme works fine with [**C# OmniSharp** 1.8.1](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) extension and [**Debugger for Unity** 1.1.0](https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug). It was developed (so the screenshots taken) with those extensions already installed.
