### ISSUE TITLE
Provide option to dismiss "add a rating" dialog

### ISSUE THREAD

**Issue by zeke** [Geri-Borbas/VSCode.Extension.eppz_Code#10]
I keep seeing a thing popping up in VS Code asking me to rate this extension. I don't want to, and I don't want to have to close the dialog more than once.

**Comment by Geri-Borbas** [comment]
It pops 4 times in a lifetime (at the 2nd, 35th, 100th, and 2000th launch) at all, you'll probably encounter two more at most.

See (ReviewPopup.ts#L17])[https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/src/ReviewPopup.ts#L17] for details.

These reviews help others to discover the extension more easily.

**Comment by zeke** [comment]
Pretty sure I've seen it more than once in the last few days, and I'm definitely past the 35 launches point. Perhaps the counter reset itself when VSCode updates itself or something?

**Comment by Geri-Borbas** [comment]
Aw, hope not, thanks for the feedback.
I'm thinking of how to test this, or simply work it around.
