### ISSUE TITLE
Remove "Rating" Popup. This isn't an iOS app.

### ISSUE THREAD

**Issue by sanbox-irl** [Geri-Borbas/VSCode.Extension.eppz_Code#13]
This pops up very frequently for me -- generally, every time I turn my computer on, I'm greeted with this. I suspect whatever caching eppz is doing to stop these pop ups isn't working, but that's really besides the point.

It should not be asking me to rate this. No other extension does this.

This is a bit obnoxious, and considering that this is an open source project, I would ask that it be removed.

**Comment by Geri-Borbas** [comment]
It should ask you for a review on the 2nd, 35th, 100th, 2000th launches, then no more.
You can see at [ReviewPopup.ts#L17](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/src/ReviewPopup.ts#L17)

<img width="782" alt="screen shot 2018-11-09 at 6 53 31" src="https://user-images.githubusercontent.com/1779614/48245678-5739e880-e3ec-11e8-9510-c42896de3b52.png">

It uses `this.context.globalState.update("launchCount", value);` to cache launch count. Were there any API update that broke this?

**Comment by Geri-Borbas** [comment]
Seems `globalState` has some issues with multiple windows: https://github.com/Microsoft/vscode/issues/55834
