### ISSUE TITLE
Intellisense disappears when installing eppz! theme

### ISSUE THREAD

**Issue by juniordiscart** [Geri-Borbas/VSCode.Extension.eppz_Code#2]
Hey,

I like the visual appearance of the theme, however, when installing, I noticed that several VS Code features don't work any longer. When installing the theme, the following things happen right away when reloading the window:
- My file icons in the file browser of VSCode have reverted back to default instead of an icon theme I use.
- Intellisense doesn't start up: it seems it isn't even loaded. Normally, when opening VSCode, it takes a few secs before the project is loaded. Initiating Intellisense gives you the "loading..." hint, while with the theme installed, it just shows the normal "word"-like hints, not actual code hints.

The firm I work in uses Unity, and on both Windows as Mac systems, the issue presents itself, as well as when working in different versions of Unity (5.3.4, 5.5 and 5.6 => different projects).
Both systems I tested on use VSCode 1.11 with the C# 1.8.1 extension. No other extensions installed.

Apart from the above description and screenshot, I can't really give you any steps to reproduce, as it seems to happen out of the box, with fresh projects.

![screen shot 2017-04-06 at 18 06 56](https://cloud.githubusercontent.com/assets/2467173/24764482/c253d8c8-1af4-11e7-9bfe-f65b7da5a5fa.png)

**Comment by Geri-Borbas** [comment]
Thanks for the detailed description! Helps a whole lot.
I'll start tracking down what causes the issue in particular later today.
Hopefully, rolling out an update even later today. 😄

**Comment by Geri-Borbas** [comment]
Yap, OmniSharp extension contributes a `csharp` language as well...

**Comment by juniordiscart** [comment]
Great for finding the source. Hope you can resolve it soon. :)

**Comment by Geri-Borbas** [comment]
...but this theme contributed a language with id `cs` for `.cs` files. I'll publish an update anytime soon, would be greatly helpful if you could test on your setup(s) as well.

**Comment by Geri-Borbas** [comment]
Yap, that was the issue.

![eppz _c _theme_103](https://cloud.githubusercontent.com/assets/1779614/24775210/245f69f2-1b1c-11e7-9e65-28fd0c390c98.png)


Thanks again for reporting that!
**1.0.31 coming in minutes.**

**Comment by juniordiscart** [comment]
Great, I look forward to using your theme! :)

**Comment by Geri-Borbas** [comment]
My pleasure to see other folks' code coloured this way. Pushes me towards rolling out more updates (colouring early returns, private variables  with `(_|__|m)` prefix, and more).

There it is, you should be able to see update (1.0.31).
Please confirm if it loads IntelliSense on your setup, so I can close the issue.

**Comment by juniordiscart** [comment]
I want to confirm that it is fixed. ;)
Thanks for the quick response and fixes! I'll spread the word of your beautiful theme.

**Comment by eppz** [comment]
There it is, you should be able to see update (1.0.31).
Please confirm if it loads IntelliSense on your setup, so I can close the issue.

🌟 Also, you may **[rate the extension on Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code)**, if you like it. It becomes more discoverable for others that way.
