### ISSUE TITLE
Add HTML support

### ISSUE THREAD

**Issue by jackesdavid** [Geri-Borbas/VSCode.Extension.eppz_Code#4]
Wow... very nice theme, one of the bestes.
Can you add html support?

Thanks in advance

**Comment by Geri-Borbas** [comment]
Thanks, glad you like it.

Adding HTML support is a lot of work, I have to add Javascript, CSS, XML / SVG, formats at least to have it reasonably covered. This seems too expensive for me, compared to how many hours I deal with those languages.

It is a consequence of this: [**eppz!** (C# theme for Unity)](https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code) is a theme for me in the first place, sharing / publishing is a side effect only. 😄

**Comment by tomByrer** [comment]
JavaScript seems to work really well for both older ES5 & newer ES2015+ code; good job!

**Comment by Neophen** [comment]
Do you have your guide on colouring I might try and extend this for html?

**Comment by Geri-Borbas** [comment]
No any particular guide. Just pick colors from the [palette image](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/images/eppz-Code_2_727px.png), while rename categories. There is even an unused green category slot.

The hardest part is composing the RegEx grammar rules, but I'm pretty sure there are solid solutions out there for HTML already (while there is always room for improvement). Some of my [insights on extending languages](https://stackoverflow.com/questions/43125093/can-i-extend-vs-code-textmate-language-grammars/43149131#43149131) may help.

**Comment by ericop** [comment]
@eppz  I tried to make the changes for you to at least get a little color in there. #12

**Comment by ericop** [comment]
@jackesdavid can you confirm that something like this this is what you were looking for?

![image](https://user-images.githubusercontent.com/5218249/45440911-9b7a6800-b68b-11e8-9400-9e491b518328.png) I too do quite a bit of `.html` editing (in angular templates) and this helps this cool :sunglasses: extension to also have a bit of syntax highlighting in those too! :hatching_chick:

**Comment by jackesdavid** [comment]
Wonderful, thanks a lot!

**Comment by ericop** [comment]
@eppz are you not on GitHub much anymore these days. Did the Microsoft purchase scare you off? 🤕

**Comment by Geri-Borbas** [comment]
Yarp, I'm in a contract actually. 😃 

The extension seems to have another issue with caching, so there may be a release where I handle both.

To just double check: Did you experience issues with review popup (like https://github.com/eppz/VSCode.Extension.eppz_Code/issues/13)?

**Comment by ericop** [comment]
I don't think so. After I read the set spots where you have it pop up, like
3rd ... 2000th I figured I'd seen it pop up a few times just because I open
and close VSCode quite often each day, so I figured I was hitting those set
number of restarts. Hope that answers what you were asking. 8vD

**Comment by ericop** [comment]
@eppz  here's for hoping you are able to release the HTML PR #12  fix and also the Feedback Review fix if you have a chance over the holidays! 🎄

**Comment by Geri-Borbas** [comment]
I'll do that. Probably I'll create an update with a separate file for html, so it won't be injected amongst the root theme rules. Perhaps I'll add some more scopes if needed. ✨

**Comment by Geri-Borbas** [comment]
The extension [**eppz! (C# theme for Unity)**](https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code) is bumped to 1.2.52 at the Marketplace containing these enhancements. Thanks again, @ericop ✨
