### ISSUE TITLE
Not working when using language "C# (Unity)"

### ISSUE THREAD

**Issue by sirius0xff** [Geri-Borbas/VSCode.Extension.eppz_Code#9]
After installed, I change the language to **_C#(Unity)_**.
But then all the text lost color.
I tried disabling all extensions except **_C#_** but without luck.

Please help guide me if there are any dependecies.
Thank you for your attention.

**Comment by Geri-Borbas** [comment]
I can't see any issues like this, I'm using it at the moment as well.
Your code may have a character at the top that breaks tokenizer perhaps.

Could you please try these [**Code Examples**]( https://github.com/eppz/VSCode.Extension.eppz_Code/tree/master/Documents/Code%20Examples)?<br />And / or post your code (with extension) that don't get tokenized?

**Comment by sirius0xff** [comment]
I tried again with different files but still not working, even the examples.
It is not tided to specific but all cs files.
One thing to correct is that it does recognize and highlight classes, but nothing else, not even keywords or primitive types.

I also tried with a fresh install of vscode, dotnet core, c# extension and the highlighter, on ubuntu in vmware player, without unity. But it shows the exact same symptome as in my windows install. It highlight built-in classes but nothing else. The intellisense is working fine.
 
Thank you.

**Comment by Geri-Borbas** [comment]
I can hardly find any aspect to grab, that could help me reproduce this.
Probably it is not true for every windows install, no other user reported similar issues.

I'm using VS Code 1.18.1, and extensions C# 1.13.1, Debugger for Unity 1.2.1, and eppz! (C# theme for Unity) 1.2.41. Could you please try the exact same configuration?

Do you have the **solution loaded** right?
Do you see **C# file type parsed** at the bottom right?

![sln](https://user-images.githubusercontent.com/1779614/32975385-0ec279d0-cc07-11e7-8ee0-f243d78c3756.png)

**Comment by sirius0xff** [comment]
Hi, thank you very much for your time and patient.
Here is my situation on windows.
( Another fresh setup on Ubuntu has the exact same symptoms, though Unity is not installed there.)

### Installed the extensions of exact versions:
(all other extensions are disabled)
![2](https://user-images.githubusercontent.com/32758498/33025729-b2b81f9c-ce49-11e7-910d-f279e4bd4018.png)


### Official C# highlight works :
(along with the vscode version)
![untitled](https://user-images.githubusercontent.com/32758498/33025093-e797bd5a-ce47-11e7-910d-e502c4fe58f2.png)

# My problem:
### eppz! (C# theme for Unity) not work:
(I tried several format settings: CRLF, LF, UTF8 w/ or w/o BOM... had no effect on the highlighting)
![3](https://user-images.githubusercontent.com/32758498/33025102-ec01c430-ce47-11e7-839a-e5d4a66656a8.png)

**Comment by Geri-Borbas** [comment]
Wow, detailed  informations. 👍 
One more thing, please **inspect if the scopes are parsed** correctly.
Run _Developer: Inspect TM Scopes_ command.

![inspect tm scopes](https://user-images.githubusercontent.com/1779614/33027143-9f2e82b8-ce12-11e7-879c-41e7ea99b002.png)

**Comment by Geri-Borbas** [comment]
You should see scopes as below.

![unityengine scopes](https://user-images.githubusercontent.com/1779614/33027066-6a25c180-ce12-11e7-9f55-76df2a68368a.png).

**Comment by Geri-Borbas** [comment]
Err, looking closely on your screenshots, you are using _"C# (Unity)"_ file type. It contains Unity specific scopes only (then merged into the existing rules).

**You should just use plain _"C# (csharp)"_**, that contains all the scope definitions (which should be set by default I suppose anyway).

![c csharp](https://user-images.githubusercontent.com/1779614/33027391-3f7fabfc-ce13-11e7-80a6-cb4717a40b98.png)

Wow, as I rolled back you have mentioned this in the very first comment actually. 😀  So just don't change the language, it will be merged anyway.

**Comment by sirius0xff** [comment]
I see...  But even if I use the C# language, it only shows the official colors?
Like the previously shown attachment below:
( opening code examples from repo has similar result )
![untitled](https://user-images.githubusercontent.com/32758498/33025093-e797bd5a-ce47-11e7-910d-e502c4fe58f2.png)

**Comment by Geri-Borbas** [comment]
🤔  Well, just select the theme.
Press `F6` and select `eppz!`.

Have you used [Color Themes](https://code.visualstudio.com/docs/getstarted/themes) before?

**Comment by sirius0xff** [comment]
lol, my fault.
I misunderstood it as kind of "extended highlighter" that just work.
Sorry for wasting your time.

**Comment by Geri-Borbas** [comment]
Sure thing, happy that you have it working!
Yap, actually themes can do more than the name suggest.
